name: 'Correction Effect Plot Strategy Plugin'
creator: 'Fábio Carneiro'
runtime: 'strategy.py'
description: |
  This plugin provides a strategy for plotting the effect
  of a correction on the data.
