name: 'Evolution Plot Strategy Plugin'
alias: 'evo-strat'
creator: 'Fábio Carneiro'
runtime: 'strategy.py'
description: |
  This plugin provides a strategy for plotting the evolution
  of a quantity as a function of scan number.
